### ISSUE TITLE
Custom Features

### ISSUE THREAD

**Issue by bradmartin333** [bradmartin333/XferSuite#121]
- [x] Ability to delete & edit features without using reset all button (#115, #111)
- [x] Turn off check on click (#114)
- [x] Verify checked boxes are being used when parsing (#113)
- [x] Investigate crash in #112

**Comment by bradmartin333** [comment]
change to a list box that user can open and edit custom feature from. omitting from plot order replaced checkbox function.

**Comment by bradmartin333** [comment]
@riversn do you need a way to delete custom features - not really an issue if unused ones pile up in the session
